apiVersion: v2
name: monitoring-stack
version: 0.1.0
type: application
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: ">=60.0.0 <100.0.0"
    